services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # обязательно для single-node
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"

  postgres-auth:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-course:
    image: postgres:16
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-learning:
    image: postgres:16
    environment:
      POSTGRES_DB: learning_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-community:
    image: postgres:16
    environment:
      POSTGRES_DB: community_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-notification:
    image: postgres:16
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - course-service
      - learning-service
      - community-service
      - notification-service

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      DB_HOST: postgres-auth
      DB_PORT: 5432
      DB_NAME: auth_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: "Q9mF4xVtL2pZaW8kYdG3sHnR6bUcJeT1iKo7PlNxYmZqV3rStUwXcAfHgJkLmNoP"
    depends_on:
      - kafka
      - postgres-auth

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      DB_HOST: postgres-user
      DB_PORT: 5432
      DB_NAME: user_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - postgres-user

  course-service:
    build:
      context: .
      dockerfile: services/course-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      DB_HOST: postgres-course
      DB_PORT: 5432
      DB_NAME: course_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      USER_SERVICE_URL: http://user-service:8082
    depends_on:
      - kafka
      - postgres-course
      - user-service

  learning-service:
    build:
      context: .
      dockerfile: services/learning-service/Dockerfile
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      DB_HOST: postgres-learning
      DB_PORT: 5432
      DB_NAME: learning_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      COURSE_SERVICE_URL: http://course-service:8083
    depends_on:
      - kafka
      - postgres-learning
      - course-service

  community-service:
    build:
      context: .
      dockerfile: services/community-service/Dockerfile
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: 8085
      DB_HOST: postgres-community
      DB_PORT: 5432
      DB_NAME: community_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      USER_SERVICE_URL: http://user-service:8082
      COURSE_SERVICE_URL: http://course-service:8083
    depends_on:
      - kafka
      - postgres-community
      - user-service
      - course-service

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    ports:
      - "8086:8086"
    environment:
      SERVER_PORT: 8086
      DB_HOST: postgres-notification
      DB_PORT: 5432
      DB_NAME: notification_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - postgres-notification