server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: users
          uri: http://user-service:8082
          predicates:
            - Path=/users/**

        - id: courses
          uri: http://course-service:8083
          predicates:
            - Path=/courses/**

        - id: learning
          uri: http://learning-service:8084
          predicates:
            - Path=/learning/**

        - id: community
          uri: http://community-service:8085
          predicates:
            - Path=/community/**

        - id: notifications
          uri: http://notification-service:8086
          predicates:
            - Path=/notifications/**